---
name: Check isort compliance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  isort_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify a relevant Python version
      - name: Install PyTorch (CPU-only)
        run: pip install torch --index-url https://download.pytorch.org/whl/cpu
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run isort check
        run: isort --check --diff .
