name: Check Import Layering

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-import-layers:
    name: Lint Import Layers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the project in editable mode with 'dev' extras
          # This will install import-linter and make the tsercom package discoverable
          pip install -e .[dev]

      - name: Run Import Linter
        run: |
          import-linter
