name: Mypy Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install PyTorch CPU
      run: pip install torch --index-url https://download.pytorch.org/whl/cpu
    - name: Install dependencies
      run: pip install -e .[dev]
    - name: Run mypy
      run: mypy tsercom/
