name: Upload to PyPI

on:
  workflow_run:  # Trigger on completion of another workflow
    workflows: ["Upload to TestPyPI"]  # Name of your TestPyPI workflow
    types:
      - completed

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if TestPyPI succeeded
    environment:
      name: pypi
      url: https://pypi.org/p/tsercom
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0  # IMPORTANT: Fetch all history for setuptools-scm

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools build setuptools-scm

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1