name: Upload to TestPyPI

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/tsercom 
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0  # IMPORTANT: Fetch all history for setuptools-scm

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-tools build setuptools-scm

      - name: Check git status for unexpected changes
        run: |
          echo "Running git status to check for dirty state..."
          git status

      - name: Discard any uncommitted changes to ensure a clean build
        run: git checkout -- .

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/  # Specify TestPyPI URL

      - name: Test Installation from TestPyPI
        run: |
          python -m venv testenv
          source testenv/bin/activate
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ tsercom