name: Publish Documentation to GitHub Pages

on:
  workflow_run:
    workflows: ["Upload to PyPI"] # Name of the PyPI publishing workflow
    types:
      - completed

jobs:
  deploy-docs:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write # Needed to push to gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for sphinx-multiversion to access tags/branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install sphinx sphinx-rtd-theme sphinx-multiversion

      - name: Build versioned documentation
        run: sh ./build_docs.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          # user_name: 'github-actions[bot]' # Optional: customize commit user
          # user_email: 'github-actions[bot]@users.noreply.github.com' # Optional: customize commit user
          # force_orphan: true # Optional: Create a new commit history for gh-pages
