name: Python Tests and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Using a recent stable version
    - name: Install dependencies
      run: |
        pip install -e .[dev]
        pip install pytest-timeout pytest-cov
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    - name: Run pytest with coverage
      run: |
        pytest --cov=tsercom --cov-report=xml --timeout=120
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: rwkeane/tsercom
