name: YAPF Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  yapf-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Consider using a .python-version file

      - name: Install yapf
        run: pip install yapf

      - name: Run yapf format check (dry run)
        id: yapf
        run: |
          yapf --diff --recursive --exclude='**/proto/*.py' .
        continue-on-error: true

      - name: Check for formatting differences
        run: |
          if [[ "${{ steps.yapf.outcome }}" == "failure" ]]; then
            echo "::error::YAPF format check failed. Please format your code."
            echo "::group::Formatting differences"
            echo "${{ steps.yapf.outputs.stdout }}"
            echo "::endgroup::"
            echo "You can format your code locally with:  yapf --recursive --in-place --exclude='**/proto/*.py' ."
            exit 1
          else:
            echo "YAPF format check passed."
          fi